// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJlH8bhd1vqKrh_MvGG8ODCxwa18GQFqk',
    appId: '1:998723869994:web:57f88fe7ac0c0a56351253',
    messagingSenderId: '998723869994',
    projectId: 'school-call-student',
    authDomain: 'school-call-student.firebaseapp.com',
    databaseURL: 'https://school-call-student-default-rtdb.firebaseio.com',
    storageBucket: 'school-call-student.appspot.com',
    measurementId: 'G-29CKLW3XZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0KR0PT1rB8nKpuY3cUvFaLeiiR1rHdsM',
    appId: '1:998723869994:android:30439e702340a022351253',
    messagingSenderId: '998723869994',
    projectId: 'school-call-student',
    databaseURL: 'https://school-call-student-default-rtdb.firebaseio.com',
    storageBucket: 'school-call-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1i3YmDMbx4vT7Rva3aSr3QqIvucDtVgc',
    appId: '1:998723869994:ios:b50aee8b9edd6bca351253',
    messagingSenderId: '998723869994',
    projectId: 'school-call-student',
    databaseURL: 'https://school-call-student-default-rtdb.firebaseio.com',
    storageBucket: 'school-call-student.appspot.com',
    iosBundleId: 'com.example.callSon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1i3YmDMbx4vT7Rva3aSr3QqIvucDtVgc',
    appId: '1:998723869994:ios:b50aee8b9edd6bca351253',
    messagingSenderId: '998723869994',
    projectId: 'school-call-student',
    databaseURL: 'https://school-call-student-default-rtdb.firebaseio.com',
    storageBucket: 'school-call-student.appspot.com',
    iosBundleId: 'com.example.callSon',
  );
}
